### ISSUE TITLE
Camera dome u h52ga with hack yi-hack-Allwinner-v2 version 0.2.6 -camera off

### ISSUE THREAD

**Issue by majkers** [roleoroleo/yi-hack_ha_integration#112]
After updating integration to latest version and hack to 0.2.6 I can't play stream in Home Assistant. In logs I see message that camera is off:

![image](https://user-images.githubusercontent.com/21099773/220973573-cad4b9b7-8132-4c50-a8b9-60056de120a0.png)

It was working OK with previous integration version. I can access last motion camera at the same time or use go2rtc integration.

Sensors also not showing real status, eg. Actually almost are all off...

![image](https://user-images.githubusercontent.com/21099773/220978369-386f5040-d5e4-4891-a193-62141a24d19e.png)

![image](https://user-images.githubusercontent.com/21099773/220978677-742faf0e-f9fa-4076-bd96-958ef27dcf48.png)
![image](https://user-images.githubusercontent.com/21099773/220978897-1e309bf7-5a1d-4d1d-81d6-3044af95cbc7.png)

One more question about those new sensors. Previously I had to disable face detection, humand deterction to make motion detection work. Now I can enable it all?

**Comment by majkers** [comment]
When restarting HA some more logs:
`2023-02-23 17:28:16.588 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry dome_u_1 for yi_hack
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 533, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/config/custom_components/yi_hack/__init__.py", line 150, in async_unload_entry
    hass.data[DOMAIN].pop(entry.entry_id)
KeyError: '255c97486a9155b7949a348dce198fc1'
2023-02-23 17:28:39.388 ERROR (SyncWorker_4) [custom_components.yi_hack.common] Failed to get status from device http://192.168.1.14/: error HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //192.168.1.14/:8080/cgi-bin/status.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4aee6860>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
2023-02-23 17:28:52.381 ERROR (SyncWorker_0) [custom_components.yi_hack.common] Failed to get status from device http://192.168.1.14/: error HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //192.168.1.14/:8080/cgi-bin/status.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f485f2950>: Failed to establish a new connection: [Errno -2] Name does not resolve'))`

**Comment by roleoroleo** [comment]
If you restart ha, the status of the cam is not updated.
I need to add a force refresh to fix this problem.
Try to restart the cam and the camera should appear "on".

About the status.json error, I don't know...
What version of ha are you using?

**Comment by majkers** [comment]
I happended on HA version 2023.1.7. Maybe this is the cause?
`Max retries exceeded with url: //192.168.1.14/:8080/cgi-bin/status.json`
why there is an extra / before port number?

**Comment by roleoroleo** [comment]
I don't know.
Never seen before.
Did you try to remove the the cam from the integration and add it again?

**Comment by majkers** [comment]
Yes I did. Ok let's leave it for now. I will wait for your next release (with fix youe mentioned above) and check it then.

**Comment by majkers** [comment]
Just installled 0.4.5 version...camera is still offline...

**Comment by majkers** [comment]
Cleaning browser cache did not help:

![image](https://user-images.githubusercontent.com/21099773/226848140-8d8a2247-c202-4afa-b106-1051a8d3ef5c.png)

**Comment by majkers** [comment]
Jus the one I mentioned above with a bottom picture.

**Comment by majkers** [comment]
Yes. I use zigbee2mqtt

**Comment by roleoroleo** [comment]
Ok, please run MQTT Explorer and check if you receive stat messages when you start the cam.

![immagine](https://user-images.githubusercontent.com/39277388/227148972-1018b588-1fb4-4e91-9a49-8a709e4cb3cb.png)

**Comment by roleoroleo** [comment]
Sometimes OTA update doesn't work properly and a fresh install is necessary.
Let me know.
