### ISSUE TITLE
HA core-2021.5.1 Compatibility

### ISSUE THREAD

**Issue by satomma** [roleoroleo/yi-hack_ha_integration#17]
Hello, is it compatible with core-2021.5.1 version of HA?
I just set it in custom_components , I see in logs a message that tells it's not tested component..
But then I cant call it anywhere... checked in integrations and no Yi object at all..

Any help?

Thanks

**Comment by roleoroleo** [comment]
> Hello, is it compatible with core-2021.5.1 version of HA?

Yes it works.

> I just set it in custom_components , I see in logs a message that tells it's not tested component..

This is the normal behavior.

> But then I cant call it anywhere... checked in integrations and no Yi object at all..

Try to clean the cache of your browser.

**Comment by satomma** [comment]
I cleared the cache, no differences..
I could install yi-hack-v5 on the camera (outdoor) and could add it as ONVIF with another integration, but would love run this one and RSVP

**Comment by roleoroleo** [comment]
Check if there are other errors in the log.

**Comment by satomma** [comment]
actually, after last reboot of HA i've this messages:

`Logger: homeassistant.loader
Source: loader.py:791
First occurred: 12:17:41 (1 occurrences)
Last logged: 12:17:41

You are using a custom integration yi_hack which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant`

and this one

`Logger: aiohttp.server
Source: components/yi/camera.py:93
First occurred: 17:55:33 (2 occurrences)
Last logged: 17:56:03

Error handling request
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/yi/camera.py", line 90, in _get_latest_video_url
    await ftp.connect(self.host)
  File "/usr/local/lib/python3.8/site-packages/aioftp/client.py", line 519, in connect
    await super().connect(host, port)
  File "/usr/local/lib/python3.8/site-packages/aioftp/client.py", line 132, in connect
    reader, writer = await open_connection(
  File "/usr/local/lib/python3.8/site-packages/aioftp/client.py", line 38, in open_connection
    transport, _ = await create_connection(lambda: protocol,
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.1.241', 21)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 74, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 135, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 131, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 486, in get
    return await self.handle(request, camera)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 503, in handle
    image = await camera.async_camera_image()
  File "/usr/src/homeassistant/homeassistant/components/yi/camera.py", line 124, in async_camera_image
    url = await self._get_latest_video_url()
  File "/usr/src/homeassistant/homeassistant/components/yi/camera.py", line 93, in _get_latest_video_url
    raise PlatformNotReady(err) from err
homeassistant.exceptions.PlatformNotReady: [Errno 111] Connect call failed ('192.168.1.241', 21)
`
Some other messages about onvif and demuxing, but don't think they're involved

**Comment by roleoroleo** [comment]
You are trying to connect to port 21 (ftp).
But this integration works with web services.
Use the same port you use for the web site (default 8080).

**Comment by satomma** [comment]
But I expect to fino integration as in readme,  then point to the camera.. actually I miss the integration at all, even if I punti the files in custom folder

**Comment by roleoroleo** [comment]
The integration is loaded because the log writes the warning "You are using a custom integration yi_hack which has not been tested by Home Assistant.".

You should find it in the list when you click "Add integeation".

In the log there are no other errors.

**Comment by satomma** [comment]
Actually I removed a configuration in configuration.yml for native yi in ha and the integration appeared, so sorry for make you loose time. Thanks

**Comment by roleoroleo** [comment]
No problem.
