### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by AaronAutomation** [roleoroleo/yi-hack_ha_integration#31]
Receiving the above error when setting up the yi-hack configuration via Integrations. MQTT is enabled and I can sub to (and see) my Yi topics via MQTT in HA Integrations. Authenticaion credentials are enabled in the yi-hack interface. RTSP stream can be viewed in VLC. Home assistant log below,

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 202, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 155, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 63, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 202, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/yi_hack/config_flow.py", line 68, in async_step_user
    response = await self.hass.async_add_executor_job(get_status, user_input)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/yi_hack/config.py", line 39, in get_status
    return response.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Invalid control character '\n' at: line 8 column 18 (char 172)

**Comment by roleoroleo** [comment]
What kind of camera is?
Did you update the hack to the last version?

**Comment by AaronAutomation** [comment]
This is a Yi Home 1080. It was on fw 0.1.7, but I've updated it to 0.1.8 and still same error.

**Comment by roleoroleo** [comment]
Please, try to run the status web service:
http://IP-CAM:8080/cgi-bin/status.json

**Comment by AaronAutomation** [comment]
{
"name":"yi-hack-allwinner-v2",
"hostname":"yi-31cc",
"fw_version":"0.1.8",
"home_version":"9.0.36.00_202011101611",
"model_suffix":"y211ga",
"ptz":"no",
"serial_number":"



FFFFFFFFFFFFFFFF",
"local_time":"Wed Jun 23 15:08:46 GMT 2021",
"uptime":"57305.03",
"load_avg":"1.74 1.44 1.47",
"total_memory":"60912",
"free_memory":"34976",
"free_sd":"2%",
"local_ip":"192.168.1.16",
"netmask":"255.255.255.0",
"gateway":"192.168.1.1",
"mac_addr":"B4:FB:E3:DB:31:CC",
"wlan_essid":"mywifi",
"wlan_strength":"46" 
}

**Comment by roleoroleo** [comment]
There is an error reading the sn.
Please send me a copy of your /tmp/mmap.info

**Comment by AaronAutomation** [comment]
[mmap.zip](https://github.com/roleoroleo/yi-hack_ha_integration/files/6703280/mmap.zip)

**Comment by AaronAutomation** [comment]
Any ideas? 
I've noticed now that my camera disconnects from the network every few hours and I need to manually reset it.. Wondering if this is related to a bad camera.

**Comment by roleoroleo** [comment]
No idea, I've never had a problem like this before.

**Comment by riccardotrisciani** [comment]
Hi, here same error:
{
"name":"yi-hack-allwinner-v2",
"hostname":"yi-cb22",
"fw_version":"0.1.8",
"home_version":"9.0.36.00_202011101611",
"model_suffix":"y211ga",
"ptz":"no",
"serial_number":"



FFFFFFFFFFFFFFFF",
"local_time":"Thu Jul 15 09:29:29 GMT 2021",
"uptime":"838.56",
"load_avg":"0.59 0.89 0.76",
"total_memory":"60912",
"free_memory":"36624",
"free_sd":"99%",
"local_ip":"192.168.178.122",
"netmask":"255.255.255.0",
"gateway":"192.168.178.1",
"mac_addr":"B4:FB:E3:DB:CB:22",
"wlan_essid":"wifi",
"wlan_strength":"44" 
}

**Comment by roleoroleo** [comment]
@riccardotrisciani 
Check this issue:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/216

**Comment by djtomybcn** [comment]
Thanks Roleorelo!
I had the same problem, and I have solved it by editing the files that you comment in the other thread.

**Comment by AaronAutomation** [comment]
> @riccardotrisciani
> Check this issue:
> [roleoroleo/yi-hack-Allwinner-v2#216](https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/216)

This resolved my camera issues as well as the HA Integration issues I was having. Thanks so much!

**Comment by roleoroleo** [comment]
I will release asap.
