### ISSUE TITLE
“Config flow could not be loaded”

### ISSUE THREAD

**Issue by ChenchaoZhao** [roleoroleo/yi-hack_ha_integration#39]
after copying to home assistant dir. the integrate cannot load properly “ Config flow could not be loaded”

```

2021-07-13 13:46:51 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration yi_hack which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-07-13 13:47:23 ERROR (MainThread) [homeassistant.setup] Setup failed for mqtt: Integration failed to initialize.
2021-07-13 13:47:23 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of yi_hack. Setup failed for dependencies: mqtt
2021-07-13 13:47:23 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 128, in post
return await super().post(request)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 63, in wrapper
result = await method(view, request, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 72, in post
result = await self._flow_mgr.async_init(
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 153, in async_init
flow, result = await task
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 171, in _async_init
flow = await self.async_create_flow(handler, context=context, data=data)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 693, in async_create_flow
await async_process_deps_reqs(self.hass, self._hass_config, integration)
File "/usr/src/homeassistant/homeassistant/setup.py", line 371, in async_process_deps_reqs
raise HomeAssistantError("Could not set up all dependencies.")
homeassistant.exceptions.HomeAssistantError: Could not set up all dependencies.
```

**Comment by roleoroleo** [comment]
Did you install mqtt?

**Comment by ChenchaoZhao** [comment]
probably not. should there be a `requirements.txt`?

**Comment by roleoroleo** [comment]
> probably not. should there be a `requirements.txt`?

If I'm not wrong, requirements is related only to python packages.
But I could take a look.
Could you please share some documents about this?

**Comment by ChenchaoZhao** [comment]
e.g. there is a requirements field in the [manifest.json](https://github.com/home-assistant/core/blob/e6e1118dd4e87867b335b5938a18f43e10636238/homeassistant/components/aurora_abb_powerone/manifest.json#L6)

I don’t know what’s the subtle difference between dependencies and requirements or how hass manages dependencies.

After adding mqtt, the error disappeared.

**Comment by roleoroleo** [comment]
According to this doc:
https://developers.home-assistant.io/docs/creating_integration_manifest/
- dependencies is used to add other components
- requirements is used to add python packages (installed by pip)

I don't know why my config doesn't work but I think it's correct.

**Comment by ChenchaoZhao** [comment]
why not make a pr to hass repo?

**Comment by roleoroleo** [comment]
Now this components is frequently updated.
When I will reach a "stable" version I will add to hass.
