### ISSUE TITLE
Update for switch entity failed

### ISSUE THREAD

**Issue by andriej** [roleoroleo/yi-hack_ha_integration#46]
There has been error thrown in log after HA restart (upgraded to 2021.9.0):
```
2021-09-01 23:02:06 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.yi_hack_allwinner_7caxxxxx_privacy fails
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in async_device_update
await task
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/yi_hack/switch.py", line 43, in update
self._state = get_privacy(self.hass, self._device_name, conf)
File "/config/custom_components/yi_hack/common.py", line 193, in get_privacy
if response is not None:
UnboundLocalError: local variable 'response' referenced before assignment
```

**Comment by roleoroleo** [comment]
My log doesn't show this error.
But try this patch:
```
--- a/custom_components/yi_hack/common.py
+++ b/custom_components/yi_hack/common.py
@@ -181,6 +181,7 @@ def get_privacy(hass, device_name, config=None):
     if user or password:
         auth = HTTPBasicAuth(user, password)

+    response = None
     try:
         response = requests.get("http://" + host + ":" + port + "/cgi-bin/privacy.sh?value=status", timeout=HTTP_TIMEOUT, auth=auth)
         if response.status_code >= 300:
```

**Comment by andriej** [comment]
@roleoroleo error is gone

**Comment by roleoroleo** [comment]
Committed:
https://github.com/roleoroleo/yi-hack_ha_integration/commit/315222b9ea96cce29adce493134c3823fd97daf5

**Comment by andriej** [comment]
Great!
