### ISSUE TITLE
Speak service error

### ISSUE THREAD

**Issue by jd1900** [roleoroleo/yi-hack_ha_integration#7]
First of all, thank you for the integration!

However, when using the speak service I get this error:

```
2021-04-27 21:35:08 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547890576640] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 18, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 439, in handle_execute_script
    await script_obj.async_run(context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1200, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 341, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 359, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 559, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 583, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 649, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 692, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in _handle_entity_call
    await result
  File "/config/custom_components/yi_hack/camera.py", line 255, in async_perform_speak
    await self.hass.async_add_executor_job(self._perform_speak, language, sentence)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/yi_hack/camera.py", line 246, in _perform_speak
    if response.json()["error"] == "true":
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting ',' delimiter or '}': line 3 column 1 (char 17)
```

I've tried installing the https://github.com/roleoroleo/yi-hack-utils downloading the .tgz into the SD Card. Then, after uncompressing, copying /bin/nanotts to /home/yi-hack/bin/nanotts and the /usr/* to to /home/yi-hack/usr/* but the is not enough space left. Then, I only copied one language to be able to copy the files. Still, it doesn't work.

Is there anything I am missing or doing wrong?

**Comment by roleoroleo** [comment]
Extract the archive in /tmp/sd/yi-hack
Not in /home/yi-hack

**Comment by jd1900** [comment]
Thank you!

After creating "yi-hack" under /tmp/sd/ and the uncompressing it there, it works quite well!
